export { default as Login } from './Login/Login'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as OrderList } from './Order/List/OrderList'
export { default as OrderEdit } from './Order/Edit/OrderEdit'
export { default as NotFound } from './NotFound/NotFound'